---
title: "Estatística básica"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

&nbsp;

&nbsp;

# Introdução
# Analise descritiva
# Probabilidade
# Inferência

# Análise de Regressão

## Introdução/Motivação

Os métodos de análise de regressão formam um conjunto de poderosas ferramentas estatisticas, que estudam a relação entre duas ou mais variaveis e também fazer predições sobre essa relação. Por ser de facil interpretação, essas ferramentas podem se aplicar nas mais diversas àreas e situações, como por exemplo: faixa salarial e nível de educação, consumo de açúcar e percentual de gordura, quantidade de fertilizante e crescimento da planta, quantidade gasta em publicidade e quantidade de vendas de um produto, consumo de contéudo na TV e faixa etária, etc. 

O termo regressão foi criado por Francis Galton no século 19 durante seu estudo sobre a relação entre a altura de pais e filhos, desenvolvido no artigo (*Regression Toward Mediocrity in Hereditary Stature*)[https://galton.org/essays/1880-1889/galton-1886-jaigi-regression-stature.pdf]. Hoje aplicamos estas tecnicas com o apoio da programação, aqui faremos uso do software RStudio.  

### Regressão Linear Simples

 + Modelo 
 + Estimação dos parâmetros
 + Análise de Variância
 + Intervalos de confiança
 + Teste de Hipótese
 + Predição
 + Resíduos *Openintro
 + Diagnostico
 + Transformações

### Regressão Linear Multipla
 
 + Forma matricial
 + Estimação dos parâmetros
 + Análise de Variância
 + Predição
 + Teste de Hipótese
 + Intervalo de Confiança

Soma extra de quadrados(?)  
Coef de determinação parcial (?)  
Reg multi padronizada (?)  
Multicolineariedade(?)  
Medidas de influência e Alavancagem (?) *Caio  

#### Regressão Polinomial
 
Regressão com intervenção (?)  
Região de confiança (?)  
Teste de Hip Linear (?)  

### Seleção de modelos

Regressão Parcial (?)   
Inflação da variância (?)   


### Regressão Não-Linear

Regressão logistica(?) *openintro

# Referência  

* Análise de Regressão  

**Azevedo, Caio L. N.**. ME 613A - Análise de regressão, Primeiro Semestre 2019. 2019. IMECC - UNICAMP. Disponível em: [https://www.ime.unicamp.br/~cnaber/Material_ME613_1S_2019.htm](https://www.ime.unicamp.br/~cnaber/Material_ME613_1S_2019.htm). Acessado em: Julho à X de 2021  

**Carvalho, B**. ME613: Análise de Regressão. Github. 2021. Disponível em: [http://me613-unicamp.github.io/](http://me613-unicamp.github.io/). Acessado em: Julho à X de 2021  

**Caffo, B**. (2019). Regression models for data science in R. Leanpub. 2019. Disponível em: [https://leanpub.com/regmods/read](https://leanpub.com/regmods/read). Acessado em: Julho à X de 2021  

**Diez, D.; Rundel, M. C.; Barr, C. D.**. Openintro Statistics. Quarta edição. Atualizado em 12 de Novembro de 2019. Versão online gratuita. Disponível em: [https://www.openintro.org/book/os/](https://www.openintro.org/book/os/). Acessado em: Julho à X de 2021  

